CONNECT TO nba12;

@C:\nba.sql;

---------------------------------------------------------------------------------

-- Ejercicio 3

DELETE FROM ESTADISTICAS
WHERE TEMPORADA = '00/01'; --127

 
-- Ejercicio 4

UPDATE JUGADORES SET PROCEDENCIA = 'Spain'; -- no me salen, osea me salen 432

-- Consultas Simples

--Ejercicio 5:

SELECT JUGADORES.NOMBRE, JUGADORES.NOMBRE_EQUIPO
FROM JUGADORES
WHERE JUGADORES.PESO > 300;

--Ejercicio 6:

SELECT EQUIPOS.NOMBRE, EQUIPOS.CIUDAD
FROM EQUIPOS
WHERE EQUIPOS.CIUDAD LIKE 'New%';

-- Ejercicio 7:

SELECT DISTINCT EQUIPOS.NOMBRE
FROM EQUIPOS, PARTIDOS
WHERE 
AND PARTIDOS.PUNTOS_LOCAL >= 100; -- no me sale

--forma correcta
WHERE PARTIDOS.PUNTOS_LOCAL - PARTIDOS.PUNTOS_VISITANTE > 100;

-- CONSULTAS MULTITABLAS

-- Ejercicio 8:

SELECT JUGADORES.NOMBRE, ESTADISTICAS.PUNTOS_POR_PARTIDO
FROM JUGADORES, ESTADISTICAS
WHERE ESTADISTICAS.JUGADOR = JUGADORES.CODIGO 
AND EQUIPOS.NOMBRE = 'Bulls'
AND ESTADISTICAS.TEMPORADA = '04/05';
--GROUP BY JUGADORES.NOMBRE, ESTADISTICAS.PUNTOS_POR_PARTIDO; -- no me sale bn

-- Ejercicio 9:

SELECT JUGADORES.NOMBRE, EQUIPOS.NOMBRE, EQUIPOS.CIUDAD, ESTADISTICAS.PUNTOS_POR_PARTIDO
FROM JUGADORES, EQUIPOS, ESTADISTICAS
WHERE ESTADISTICAS.JUGADOR = JUGADORES.CODIGO AND JUGADORES.NOMBRE_EQUIPO = EQUIPOS.NOMBRE
AND ESTADISTICAS.TEMPORADA = '07/08'
AND JUGADORES.PESO > 300;
--GROUP BY JUGADORES.NOMBRE,  EQUIPOS.NOMBRE, EQUIPOS.CIUDAD, ESTADISTICAS.PUNTOS_POR_PARTIDO;

-- CONSULTAS FUNCIONES AGRUPADAS 

-- EJercicio 10:

SELECT JUGADORES.NOMBRE_EQUIPO, MAX(JUGADORES.PESO), MIN(JUGADORES.PESO)
FROM JUGADORES
WHERE JUGADORES.NOMBRE_EQUIPO = 'Knicks'
GROUP BY JUGADORES.NOMBRE_EQUIPO; 

-- Ejercicio 11:

SELECT ESTADISTICAS.TEMPORADA, COUNT(ESTADISTICAS.JUGADOR)
FROM ESTADISTICAS
GROUP BY ESTADISTICAS.TEMPORADA;

-- Ejercicio 12:

SELECT JUGADORES.NOMBRE_EQUIPO, AVG(JUGADORES.PESO)
FROM JUGADORES, EQUIPOS
WHERE JUGADORES.NOMBRE_EQUIPO = EQUIPOS.NOMBRE
AND EQUIPOS.CIUDAD = 'Los Angeles'
GROUP BY JUGADORES.NOMBRE_EQUIPO
HAVING AVG(JUGADORES.PESO) > 200;

-- Ejercicio 13:

SELECT JUGADORES.NOMBRE_EQUIPO
FROM JUGADORES
WHERE JUGADORES.PESO > 180
GROUP BY JUGADORES.NOMBRE_EQUIPO
ORDER BY JUGADORES.NOMBRE_EQUIPO DESC
FETCH FIRST 4 ROWS ONLY; -- no me sale bn, no se corresponde con la solucón

-- este seria realmente...

SELECT JUGADORES.NOMBRE_EQUIPO, MIN(JUGADORES.PESO)
FROM JUGADORES
GROUP BY JUGADORES.NOMBRE_EQUIPO
HAVING MIN(JUGADORES.PESO) > 180
ORDER BY MIN(JUGADORES.PESO) DESC;

-- SUBCONSULTAS

-- Ejercicio 14:

SELECT DISTINCT JUGADORES.NOMBRE
FROM JUGADORES, EQUIPOS
WHERE JUGADORES.NOMBRE_EQUIPO = EQUIPOS.NOMBRE
AND EQUIPOS.CONFERENCIA NOT IN (

SELECT EQUIPOS.CONFERENCIA
FROM EQUIPOS
WHERE EQUIPOS.CONFERENCIA = 'East'
); -- no me sale

-- esto sería realmente...

SELECT JUGADORES.NOMBRE
FROM JUGADORES
WHERE JUGADORES.NOMBRE_EQUIPO NOT IN (

SELECT EQUIPOS.NOMBRE
FROM EQUIPOS
WHERE EQUIPOS.CONFERENCIA = 'East'
); --este ejercicio no sale bn... asique no contó en el examen

-- Ejercicio 15:

SELECT COUNT(DISTINCT EQUIPOS.NOMBRE)
FROM EQUIPOS
WHERE EQUIPOS.NOMBRE IN (

SELECT DISTINCT EQUIPOS.NOMBRE
FROM EQUIPOS, JUGADORES
WHERE EQUIPOS.NOMBRE = JUGADORES.NOMBRE_EQUIPO
GROUP BY EQUIPOS.NOMBRE
HAVING COUNT(DISTINCT JUGADORES.PROCEDENCIA) > 14
); -- corregido y hecho posteriormente al examen

-- Ejercicio 16:

SELECT EQUIPOS.NOMBRE, EQUIPOS.CIUDAD
FROM EQUIPOS
WHERE EQUIPOS.NOMBRE IN (

SELECT PARTIDOS.EQUIPO_LOCAL 
FROM PARTIDOS
WHERE PARTIDOS.TEMPORADA = '03/04'
GROUP BY PARTIDOS.EQUIPO_LOCAL
ORDER BY SUM(PARTIDOS.PUNTOS_LOCAL) DESC
FETCH FIRST 3 ROWS ONLY
); -- corregido y hecho posteriormente al examen