

CREATE TABLE MARCAS
(
 COD_MARCA VARCHAR2(4)  PRIMARY KEY, 
 NOMBRE VARCHAR2(20) NOT NULL,
 CIUDAD VARCHAR2(20) 
);

CREATE TABLE COCHES
(
 COD_COCHE  VARCHAR2(3)  PRIMARY KEY,
 COD_MARCA VARCHAR2(4) NOT NULL,
 TIPO VARCHAR2(20),
 MODELO VARCHAR2(20)
);

CREATE TABLE CONCESIONARIOS
(
 COD_CONCESIONARIO VARCHAR2(4) PRIMARY KEY,
 NOMBRE VARCHAR2(20) NOT NULL,
 CIUDAD VARCHAR2(20) NOT NULL
);

CREATE TABLE DISTRIBUCIONES
(
 COD_CONCESIONARIO VARCHAR2(4),
 COD_COCHE VARCHAR2(3),
 CANTIDAD NUMBER(3),
 CONSTRAINT PK_DISTRIBUCIONES PRIMARY KEY (COD_CONCESIONARIO,COD_COCHE)
);

CREATE TABLE VENTAS
(
 DNI VARCHAR2(4),
 COD_CONCESIONARIO VARCHAR2(4),
 COD_COCHE VARCHAR2(3),
 COLOR VARCHAR2(20) DEFAULT 'BLANCO',
 PRIMARY KEY (DNI,COD_COCHE, COD_CONCESIONARIO)
);

