ALTER TABLE DISTRIBUCIONES 
	ADD CONSTRAINT FK_CONCES_DIST FOREIGN KEY (COD_CONCESIONARIO) REFERENCES CONCESIONARIOS (COD_CONCESIONARIO);
ALTER TABLE DISTRIBUCIONES	ADD CONSTRAINT FK_COCHES_DIST FOREIGN KEY (COD_COCHE) REFERENCES COCHES (COD_COCHE);
ALTER TABLE VENTAS 
	ADD CONSTRAINT FK_COCHES_VENT FOREIGN KEY (COD_COCHE) REFERENCES COCHES (COD_COCHE) ;
ALTER TABLE VENTAS	ADD CONSTRAINT FK_CONCES_VENT FOREIGN KEY (COD_CONCESIONARIO) REFERENCES CONCESIONARIOS (COD_CONCESIONARIO); 
ALTER TABLE VENTAS	ADD CONSTRAINT FK_CLIENT_VENT FOREIGN KEY (DNI) REFERENCES CLIENTES (DNI);
