DROP TABLE PEDIDOS;
DROP TABLE CLIENTES;
DROP TABLE PRODUCTOS;
DROP TABLE EMPLEADOS;

CREATE TABLE EMPLEADOS (
    COD_EMPLEADO	INT             PRIMARY KEY,
    APELLIDO            VARCHAR2(40)    NOT NULL,
    OFICIO              VARCHAR2(40)    NOT NULL,
    DIRECTOR            INT,
    FECHA_ALTA          DATE            NOT NULL,
    SALARIO             INT,
    COMISION            INT,
    COD_DEPARTAMENTO    INT             NOT NULL
);

CREATE TABLE CLIENTES (
    COD_CLIENTE	        INT             PRIMARY KEY,
    NOMBRE              VARCHAR2(40)    NOT NULL,
    LOCALIDAD           VARCHAR2(40)    NOT NULL,
    COD_VENDEDOR        INT             NOT NULL,
    DEBE                INT             NOT NULL,
    LIMITE_CREDITO      INT             NOT NULL
);

CREATE TABLE PRODUCTOS (
    COD_PRODUCTO	INT             PRIMARY KEY,
    DESCRIPCION         VARCHAR2(50)    NOT NULL,
    PRECIO_ACTUAL       INT,
    STOCK_DISPONIBLE    INT             NOT NULL
);

CREATE TABLE PEDIDOS (
    cod_PEDIDO 	        INT             PRIMARY KEY,
    COD_PRODUCTO	INT,
    COD_CLIENTE         INT,
    UNIDADES            INT             NOT NULL,
    FECHA_PEDIDO        DATE            NOT NULL   
);


ALTER TABLE EMPLEADOS   ADD CONSTRAINT FK_EMPLEADOS_EMPLEADOS       FOREIGN KEY (DIRECTOR)          REFERENCES EMPLEADOS (COD_EMPLEADO);
ALTER TABLE EMPLEADOS   ADD CONSTRAINT FK_EMPLEADOS_DEPARTAMENTOS   FOREIGN KEY (COD_DEPARTAMENTO)  REFERENCES DEPARTAMENTOS (COD_DEPARTAMENTO);
ALTER TABLE CLIENTES    ADD CONSTRAINT FK_CLIENTES_EMPLEADOS        FOREIGN KEY (COD_VENDEDOR)      REFERENCES EMPLEADOS (COD_EMPLEADO);
	
ALTER TABLE PEDIDOS	ADD CONSTRAINT FK_PEDIDOS_CLIENTES    	    FOREIGN KEY (COD_CLIENTE)       REFERENCES CLIENTES (COD_CLIENTE);
ALTER TABLE PEDIDOS	ADD CONSTRAINT FK_PEDIDOS_PRODUCTOS         FOREIGN KEY (COD_PRODUCTO)      REFERENCES PRODUCTOS (COD_PRODUCTO);

COMMIT WORK;
  
