CREATE TABLE EMPLEADOS (
NIF VARCHAR(10),
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
DIRECCION VARCHAR(20),
PUESTO VARCHAR(20)
); 

CREATE VIEW PUESTO AS SELECT NOMBRE, APELLIDO, PUESTO FROM EMPLEADOS;


