DROP TABLE TRABAJOS CASCADE CONSTRAINT;

DROP TABLE MECANICOS CASCADE CONSTRAINT;

DROP TABLE COCHES CASCADE CONSTRAINT;



CREATE TABLE COCHES 
(
 MATRICULA VARCHAR2(8) PRIMARY KEY,
 MARCA VARCHAR2(15),
 MODELO VARCHAR2(15) NOT NULL,
 AÑO_FABRICACION NUMBER(4) NOT NULL
);


CREATE TABLE MECANICOS 
(
 DNI VARCHAR2(9) PRIMARY KEY,
 APELLIDOS VARCHAR(100) NOT NULL,
 NOMBRE VARCHAR2(20) NOT NULL,
 PUESTO VARCHAR2(15),
 SALARIO NUMBER NOT NULL,
 PARCIAL VARCHAR2(1) DEFAULT 0,
 TELEFONO VARCHAR(10)
);

CREATE TABLE TRABAJOS 
(
 MATRICULA VARCHAR2(8),
 DNI VARCHAR2(9),
 HORAS NUMBER(3,1) CHECK (HORAS>=0.5),
 FECHA_REPARACION DATE
);



ALTER TABLE trabajos ADD  PRIMARY KEY (MATRICULA,DNI);

ALTER TABLE trabajos ADD  CONSTRAINT FK_DNI FOREIGN KEY (DNI) REFERENCES mecanicos (DNI);

ALTER TABLE trabajos ADD  CONSTRAINT FK_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES coches (MATRICULA);

COMMIT;
